language: java
jdk:
  - oraclejdk8
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g protractor
  - npm install -g mocha
install:
  - npm install
  - bower install
  - webdriver-manager update
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - curl -L http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar > selenium.jar
  - sudo ln -s /usr/lib/firefox/firefox /usr/lib/firefox/firefox-bin
script:
  - grunt unit-test
  - gradle flywayMigrate
  - gradle build
  - cd build/libs
  - chmod a+x sbangular.jar
  - "nohup java -jar sbangular.jar > ../../sbangular.log &"
  - sleep 30
  - cd ../../
  - PATH=$PATH:/usr/lib/firefox java -jar selenium.jar > /dev/null 2> selenium_output.log &
  - sleep 10
  - grunt e2e
after_script: 
  # Print logs and outputs for debugging.
  - cat selenium_output.log
  - cat sbangular.log
